/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables;


import com.duoduo.schema.DuoduoOrder;
import com.duoduo.schema.Keys;
import com.duoduo.schema.tables.records.OrderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order extends TableImpl<OrderRecord> {

    private static final long serialVersionUID = 1482426849;

    /**
     * The reference instance of <code>duoduo_order.order</code>
     */
    public static final Order ORDER = new Order();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderRecord> getRecordType() {
        return OrderRecord.class;
    }

    /**
     * The column <code>duoduo_order.order.id</code>.
     */
    public final TableField<OrderRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>duoduo_order.order.inner_status</code>. 0-已取消,1-待确认,2-已备货,3-已发货,4-已签收,5-已收款,41-退签中,42-已退签
     */
    public final TableField<OrderRecord, Byte> INNER_STATUS = createField("inner_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-已取消,1-待确认,2-已备货,3-已发货,4-已签收,5-已收款,41-退签中,42-已退签");

    /**
     * The column <code>duoduo_order.order.inner_create_time</code>.
     */
    public final TableField<OrderRecord, Timestamp> INNER_CREATE_TIME = createField("inner_create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>duoduo_order.order.inner_update_time</code>.
     */
    public final TableField<OrderRecord, Timestamp> INNER_UPDATE_TIME = createField("inner_update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>duoduo_order.order.order_id</code>.
     */
    public final TableField<OrderRecord, String> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.user_id</code>.
     */
    public final TableField<OrderRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.user_type</code>.
     */
    public final TableField<OrderRecord, String> USER_TYPE = createField("user_type", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.user_name</code>.
     */
    public final TableField<OrderRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo_order.order.spec_desc</code>.
     */
    public final TableField<OrderRecord, String> SPEC_DESC = createField("spec_desc", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo_order.order.product_id</code>.
     */
    public final TableField<OrderRecord, String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.combo_id</code>.
     */
    public final TableField<OrderRecord, String> COMBO_ID = createField("combo_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.shop_id</code>.
     */
    public final TableField<OrderRecord, String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.shop_name</code>.
     */
    public final TableField<OrderRecord, String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo_order.order.pay_type</code>.
     */
    public final TableField<OrderRecord, String> PAY_TYPE = createField("pay_type", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.combo_amount</code>.
     */
    public final TableField<OrderRecord, String> COMBO_AMOUNT = createField("combo_amount", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.combo_num</code>.
     */
    public final TableField<OrderRecord, String> COMBO_NUM = createField("combo_num", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.post_amount</code>.
     */
    public final TableField<OrderRecord, String> POST_AMOUNT = createField("post_amount", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.total_amount</code>.
     */
    public final TableField<OrderRecord, String> TOTAL_AMOUNT = createField("total_amount", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.post_addr</code>.
     */
    public final TableField<OrderRecord, String> POST_ADDR = createField("post_addr", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo_order.order.post_code</code>.
     */
    public final TableField<OrderRecord, String> POST_CODE = createField("post_code", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.post_receiver</code>.
     */
    public final TableField<OrderRecord, String> POST_RECEIVER = createField("post_receiver", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.post_tel</code>.
     */
    public final TableField<OrderRecord, String> POST_TEL = createField("post_tel", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.logistics_id</code>.
     */
    public final TableField<OrderRecord, String> LOGISTICS_ID = createField("logistics_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.logistics_code</code>.
     */
    public final TableField<OrderRecord, String> LOGISTICS_CODE = createField("logistics_code", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.logistics_time</code>.
     */
    public final TableField<OrderRecord, String> LOGISTICS_TIME = createField("logistics_time", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo_order.order.receipt_time</code>.
     */
    public final TableField<OrderRecord, String> RECEIPT_TIME = createField("receipt_time", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo_order.order.buyer_words</code>.
     */
    public final TableField<OrderRecord, String> BUYER_WORDS = createField("buyer_words", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo_order.order.cancel_reson</code>.
     */
    public final TableField<OrderRecord, String> CANCEL_RESON = createField("cancel_reson", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo_order.order.remark</code>.
     */
    public final TableField<OrderRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo_order.order.order_status</code>.
     */
    public final TableField<OrderRecord, String> ORDER_STATUS = createField("order_status", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.status</code>.
     */
    public final TableField<OrderRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.create_time</code>.
     */
    public final TableField<OrderRecord, String> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.update_time</code>.
     */
    public final TableField<OrderRecord, String> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.final_status</code>.
     */
    public final TableField<OrderRecord, String> FINAL_STATUS = createField("final_status", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.source_id</code>.
     */
    public final TableField<OrderRecord, String> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.source_type</code>.
     */
    public final TableField<OrderRecord, String> SOURCE_TYPE = createField("source_type", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.seller_words</code>.
     */
    public final TableField<OrderRecord, String> SELLER_WORDS = createField("seller_words", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo_order.order.service</code>.
     */
    public final TableField<OrderRecord, String> SERVICE = createField("service", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo_order.order.op_id</code>.
     */
    public final TableField<OrderRecord, String> OP_ID = createField("op_id", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.op_time</code>.
     */
    public final TableField<OrderRecord, String> OP_TIME = createField("op_time", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.cancel_remark</code>.
     */
    public final TableField<OrderRecord, String> CANCEL_REMARK = createField("cancel_remark", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.urg_cnt</code>.
     */
    public final TableField<OrderRecord, String> URG_CNT = createField("urg_cnt", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.product_name</code>.
     */
    public final TableField<OrderRecord, String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.repeat</code>.
     */
    public final TableField<OrderRecord, String> REPEAT = createField("repeat", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo_order.order.logistics_detail</code>.
     */
    public final TableField<OrderRecord, String> LOGISTICS_DETAIL = createField("logistics_detail", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo_order.order.attention</code>.
     */
    public final TableField<OrderRecord, String> ATTENTION = createField("attention", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.tel_area</code>.
     */
    public final TableField<OrderRecord, String> TEL_AREA = createField("tel_area", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.combo_name</code>.
     */
    public final TableField<OrderRecord, String> COMBO_NAME = createField("combo_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.order.is_follow_arbitration</code>.
     */
    public final TableField<OrderRecord, String> IS_FOLLOW_ARBITRATION = createField("is_follow_arbitration", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo_order.order.aftersale</code>.
     */
    public final TableField<OrderRecord, String> AFTERSALE = createField("aftersale", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo_order.order.product</code>.
     */
    public final TableField<OrderRecord, String> PRODUCT = createField("product", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>duoduo_order.order</code> table reference
     */
    public Order() {
        this("order", null);
    }

    /**
     * Create an aliased <code>duoduo_order.order</code> table reference
     */
    public Order(String alias) {
        this(alias, ORDER);
    }

    private Order(String alias, Table<OrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private Order(String alias, Table<OrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DuoduoOrder.DUODUO_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrderRecord, Long> getIdentity() {
        return Keys.IDENTITY_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderRecord>>asList(Keys.KEY_ORDER_PRIMARY, Keys.KEY_ORDER_U_ORDER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Order as(String alias) {
        return new Order(alias, this);
    }

    /**
     * Rename this table
     */
    public Order rename(String name) {
        return new Order(name, null);
    }
}
