/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables;


import com.duoduo.schema.DuoduoOrder;
import com.duoduo.schema.Keys;
import com.duoduo.schema.tables.records.RetreatGoodRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RetreatGood extends TableImpl<RetreatGoodRecord> {

    private static final long serialVersionUID = 712535276;

    /**
     * The reference instance of <code>duoduo_order.retreat_good</code>
     */
    public static final RetreatGood RETREAT_GOOD = new RetreatGood();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RetreatGoodRecord> getRecordType() {
        return RetreatGoodRecord.class;
    }

    /**
     * The column <code>duoduo_order.retreat_good.id</code>.
     */
    public final TableField<RetreatGoodRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>duoduo_order.retreat_good.status</code>. 0-其他原因,1-退货中,2-已退货,3-已退款
     */
    public final TableField<RetreatGoodRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "0-其他原因,1-退货中,2-已退货,3-已退款");

    /**
     * The column <code>duoduo_order.retreat_good.order_id</code>.
     */
    public final TableField<RetreatGoodRecord, String> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo_order.retreat_good.express_order_no</code>. 快递单号
     */
    public final TableField<RetreatGoodRecord, String> EXPRESS_ORDER_NO = createField("express_order_no", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "快递单号");

    /**
     * The column <code>duoduo_order.retreat_good.express_company_name</code>. 快递公司
     */
    public final TableField<RetreatGoodRecord, String> EXPRESS_COMPANY_NAME = createField("express_company_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "快递公司");

    /**
     * The column <code>duoduo_order.retreat_good.retreat_reason</code>. 退货原因
     */
    public final TableField<RetreatGoodRecord, String> RETREAT_REASON = createField("retreat_reason", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "退货原因");

    /**
     * The column <code>duoduo_order.retreat_good.express_amount</code>. 快递费
     */
    public final TableField<RetreatGoodRecord, BigDecimal> EXPRESS_AMOUNT = createField("express_amount", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "快递费");

    /**
     * The column <code>duoduo_order.retreat_good.retreat_amount</code>. 退款金额
     */
    public final TableField<RetreatGoodRecord, BigDecimal> RETREAT_AMOUNT = createField("retreat_amount", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "退款金额");

    /**
     * The column <code>duoduo_order.retreat_good.remark</code>. 备注
     */
    public final TableField<RetreatGoodRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "备注");

    /**
     * The column <code>duoduo_order.retreat_good.create_time</code>.
     */
    public final TableField<RetreatGoodRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>duoduo_order.retreat_good.update_time</code>.
     */
    public final TableField<RetreatGoodRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>duoduo_order.retreat_good</code> table reference
     */
    public RetreatGood() {
        this("retreat_good", null);
    }

    /**
     * Create an aliased <code>duoduo_order.retreat_good</code> table reference
     */
    public RetreatGood(String alias) {
        this(alias, RETREAT_GOOD);
    }

    private RetreatGood(String alias, Table<RetreatGoodRecord> aliased) {
        this(alias, aliased, null);
    }

    private RetreatGood(String alias, Table<RetreatGoodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DuoduoOrder.DUODUO_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RetreatGoodRecord, Long> getIdentity() {
        return Keys.IDENTITY_RETREAT_GOOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RetreatGoodRecord> getPrimaryKey() {
        return Keys.KEY_RETREAT_GOOD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RetreatGoodRecord>> getKeys() {
        return Arrays.<UniqueKey<RetreatGoodRecord>>asList(Keys.KEY_RETREAT_GOOD_PRIMARY, Keys.KEY_RETREAT_GOOD_U_ORDER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RetreatGood as(String alias) {
        return new RetreatGood(alias, this);
    }

    /**
     * Rename this table
     */
    public RetreatGood rename(String name) {
        return new RetreatGood(name, null);
    }
}
