/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables;


import com.duoduo.schema.Duoduo;
import com.duoduo.schema.Keys;
import com.duoduo.schema.tables.records.EhOrderRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrder extends TableImpl<EhOrderRecord> {

    private static final long serialVersionUID = -562133481;

    /**
     * The reference instance of <code>duoduo.eh_order</code>
     */
    public static final EhOrder EH_ORDER = new EhOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhOrderRecord> getRecordType() {
        return EhOrderRecord.class;
    }

    /**
     * The column <code>duoduo.eh_order.id</code>.
     */
    public final TableField<EhOrderRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>duoduo.eh_order.order_id</code>.
     */
    public final TableField<EhOrderRecord, String> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.user_id</code>.
     */
    public final TableField<EhOrderRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.user_name</code>.
     */
    public final TableField<EhOrderRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo.eh_order.spec_desc</code>.
     */
    public final TableField<EhOrderRecord, String> SPEC_DESC = createField("spec_desc", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo.eh_order.product_id</code>.
     */
    public final TableField<EhOrderRecord, String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.combo_id</code>.
     */
    public final TableField<EhOrderRecord, String> COMBO_ID = createField("combo_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.combo_name</code>.
     */
    public final TableField<EhOrderRecord, String> COMBO_NAME = createField("combo_name", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo.eh_order.shop_id</code>.
     */
    public final TableField<EhOrderRecord, String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.shop_name</code>.
     */
    public final TableField<EhOrderRecord, String> SHOP_NAME = createField("shop_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo.eh_order.product_name</code>.
     */
    public final TableField<EhOrderRecord, String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>duoduo.eh_order.combo_num</code>.
     */
    public final TableField<EhOrderRecord, String> COMBO_NUM = createField("combo_num", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.post_addr</code>.
     */
    public final TableField<EhOrderRecord, String> POST_ADDR = createField("post_addr", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo.eh_order.post_receiver</code>.
     */
    public final TableField<EhOrderRecord, String> POST_RECEIVER = createField("post_receiver", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>duoduo.eh_order.post_tel</code>.
     */
    public final TableField<EhOrderRecord, String> POST_TEL = createField("post_tel", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.logistics_code</code>.
     */
    public final TableField<EhOrderRecord, String> LOGISTICS_CODE = createField("logistics_code", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>duoduo.eh_order.buyer_words</code>.
     */
    public final TableField<EhOrderRecord, String> BUYER_WORDS = createField("buyer_words", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo.eh_order.order_status</code>.
     */
    public final TableField<EhOrderRecord, String> ORDER_STATUS = createField("order_status", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.logistics_time</code>.
     */
    public final TableField<EhOrderRecord, String> LOGISTICS_TIME = createField("logistics_time", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.receipt_time</code>.
     */
    public final TableField<EhOrderRecord, String> RECEIPT_TIME = createField("receipt_time", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.seller_words</code>.
     */
    public final TableField<EhOrderRecord, String> SELLER_WORDS = createField("seller_words", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>duoduo.eh_order.user_type</code>.
     */
    public final TableField<EhOrderRecord, String> USER_TYPE = createField("user_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.repeat</code>.
     */
    public final TableField<EhOrderRecord, String> REPEAT = createField("repeat", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.logistics_detail</code>.
     */
    public final TableField<EhOrderRecord, String> LOGISTICS_DETAIL = createField("logistics_detail", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo.eh_order.tel_area</code>.
     */
    public final TableField<EhOrderRecord, String> TEL_AREA = createField("tel_area", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>duoduo.eh_order.aftersale</code>.
     */
    public final TableField<EhOrderRecord, String> AFTERSALE = createField("aftersale", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo.eh_order.product</code>.
     */
    public final TableField<EhOrderRecord, String> PRODUCT = createField("product", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>duoduo.eh_order.sell_num</code>.
     */
    public final TableField<EhOrderRecord, String> SELL_NUM = createField("sell_num", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * Create a <code>duoduo.eh_order</code> table reference
     */
    public EhOrder() {
        this("eh_order", null);
    }

    /**
     * Create an aliased <code>duoduo.eh_order</code> table reference
     */
    public EhOrder(String alias) {
        this(alias, EH_ORDER);
    }

    private EhOrder(String alias, Table<EhOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private EhOrder(String alias, Table<EhOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Duoduo.DUODUO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EhOrderRecord, Long> getIdentity() {
        return Keys.IDENTITY_EH_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EhOrderRecord> getPrimaryKey() {
        return Keys.KEY_EH_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EhOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<EhOrderRecord>>asList(Keys.KEY_EH_ORDER_PRIMARY, Keys.KEY_EH_ORDER_U_ORDER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhOrder as(String alias) {
        return new EhOrder(alias, this);
    }

    /**
     * Rename this table
     */
    public EhOrder rename(String name) {
        return new EhOrder(name, null);
    }
}
