/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables.records;


import com.duoduo.schema.tables.EhOrder;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrderRecord extends UpdatableRecordImpl<EhOrderRecord> {

    private static final long serialVersionUID = -194861561;

    /**
     * Setter for <code>duoduo.eh_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>duoduo.eh_order.order_id</code>.
     */
    public void setOrderId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>duoduo.eh_order.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>duoduo.eh_order.user_name</code>.
     */
    public void setUserName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.user_name</code>.
     */
    public String getUserName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>duoduo.eh_order.spec_desc</code>.
     */
    public void setSpecDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.spec_desc</code>.
     */
    public String getSpecDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>duoduo.eh_order.product_id</code>.
     */
    public void setProductId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.product_id</code>.
     */
    public String getProductId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>duoduo.eh_order.combo_id</code>.
     */
    public void setComboId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.combo_id</code>.
     */
    public String getComboId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>duoduo.eh_order.combo_name</code>.
     */
    public void setComboName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.combo_name</code>.
     */
    public String getComboName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>duoduo.eh_order.shop_id</code>.
     */
    public void setShopId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>duoduo.eh_order.shop_name</code>.
     */
    public void setShopName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.shop_name</code>.
     */
    public String getShopName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>duoduo.eh_order.product_name</code>.
     */
    public void setProductName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.product_name</code>.
     */
    public String getProductName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>duoduo.eh_order.combo_num</code>.
     */
    public void setComboNum(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.combo_num</code>.
     */
    public String getComboNum() {
        return (String) get(11);
    }

    /**
     * Setter for <code>duoduo.eh_order.post_addr</code>.
     */
    public void setPostAddr(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.post_addr</code>.
     */
    public String getPostAddr() {
        return (String) get(12);
    }

    /**
     * Setter for <code>duoduo.eh_order.post_receiver</code>.
     */
    public void setPostReceiver(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.post_receiver</code>.
     */
    public String getPostReceiver() {
        return (String) get(13);
    }

    /**
     * Setter for <code>duoduo.eh_order.post_tel</code>.
     */
    public void setPostTel(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.post_tel</code>.
     */
    public String getPostTel() {
        return (String) get(14);
    }

    /**
     * Setter for <code>duoduo.eh_order.logistics_code</code>.
     */
    public void setLogisticsCode(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.logistics_code</code>.
     */
    public String getLogisticsCode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>duoduo.eh_order.buyer_words</code>.
     */
    public void setBuyerWords(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.buyer_words</code>.
     */
    public String getBuyerWords() {
        return (String) get(16);
    }

    /**
     * Setter for <code>duoduo.eh_order.order_status</code>.
     */
    public void setOrderStatus(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.order_status</code>.
     */
    public String getOrderStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>duoduo.eh_order.logistics_time</code>.
     */
    public void setLogisticsTime(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.logistics_time</code>.
     */
    public String getLogisticsTime() {
        return (String) get(18);
    }

    /**
     * Setter for <code>duoduo.eh_order.receipt_time</code>.
     */
    public void setReceiptTime(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.receipt_time</code>.
     */
    public String getReceiptTime() {
        return (String) get(19);
    }

    /**
     * Setter for <code>duoduo.eh_order.seller_words</code>.
     */
    public void setSellerWords(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.seller_words</code>.
     */
    public String getSellerWords() {
        return (String) get(20);
    }

    /**
     * Setter for <code>duoduo.eh_order.user_type</code>.
     */
    public void setUserType(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.user_type</code>.
     */
    public String getUserType() {
        return (String) get(21);
    }

    /**
     * Setter for <code>duoduo.eh_order.repeat</code>.
     */
    public void setRepeat(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.repeat</code>.
     */
    public String getRepeat() {
        return (String) get(22);
    }

    /**
     * Setter for <code>duoduo.eh_order.logistics_detail</code>.
     */
    public void setLogisticsDetail(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.logistics_detail</code>.
     */
    public String getLogisticsDetail() {
        return (String) get(23);
    }

    /**
     * Setter for <code>duoduo.eh_order.tel_area</code>.
     */
    public void setTelArea(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.tel_area</code>.
     */
    public String getTelArea() {
        return (String) get(24);
    }

    /**
     * Setter for <code>duoduo.eh_order.aftersale</code>.
     */
    public void setAftersale(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.aftersale</code>.
     */
    public String getAftersale() {
        return (String) get(25);
    }

    /**
     * Setter for <code>duoduo.eh_order.product</code>.
     */
    public void setProduct(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.product</code>.
     */
    public String getProduct() {
        return (String) get(26);
    }

    /**
     * Setter for <code>duoduo.eh_order.sell_num</code>.
     */
    public void setSellNum(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>duoduo.eh_order.sell_num</code>.
     */
    public String getSellNum() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EhOrderRecord
     */
    public EhOrderRecord() {
        super(EhOrder.EH_ORDER);
    }

    /**
     * Create a detached, initialised EhOrderRecord
     */
    public EhOrderRecord(Long id, String orderId, String userId, String userName, String specDesc, String productId, String comboId, String comboName, String shopId, String shopName, String productName, String comboNum, String postAddr, String postReceiver, String postTel, String logisticsCode, String buyerWords, String orderStatus, String logisticsTime, String receiptTime, String sellerWords, String userType, String repeat, String logisticsDetail, String telArea, String aftersale, String product, String sellNum) {
        super(EhOrder.EH_ORDER);

        set(0, id);
        set(1, orderId);
        set(2, userId);
        set(3, userName);
        set(4, specDesc);
        set(5, productId);
        set(6, comboId);
        set(7, comboName);
        set(8, shopId);
        set(9, shopName);
        set(10, productName);
        set(11, comboNum);
        set(12, postAddr);
        set(13, postReceiver);
        set(14, postTel);
        set(15, logisticsCode);
        set(16, buyerWords);
        set(17, orderStatus);
        set(18, logisticsTime);
        set(19, receiptTime);
        set(20, sellerWords);
        set(21, userType);
        set(22, repeat);
        set(23, logisticsDetail);
        set(24, telArea);
        set(25, aftersale);
        set(26, product);
        set(27, sellNum);
    }
}
