/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables.records;


import com.duoduo.schema.tables.Order;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> {

    private static final long serialVersionUID = -731876809;

    /**
     * Setter for <code>duoduo_order.order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>duoduo_order.order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>duoduo_order.order.inner_status</code>. 0-已取消,1-待确认,2-已备货,3-已发货,4-已签收,5-已收款,41-退签中,42-已退签
     */
    public void setInnerStatus(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>duoduo_order.order.inner_status</code>. 0-已取消,1-待确认,2-已备货,3-已发货,4-已签收,5-已收款,41-退签中,42-已退签
     */
    public Byte getInnerStatus() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>duoduo_order.order.inner_create_time</code>.
     */
    public void setInnerCreateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>duoduo_order.order.inner_create_time</code>.
     */
    public Timestamp getInnerCreateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>duoduo_order.order.inner_update_time</code>.
     */
    public void setInnerUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>duoduo_order.order.inner_update_time</code>.
     */
    public Timestamp getInnerUpdateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>duoduo_order.order.order_id</code>.
     */
    public void setOrderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>duoduo_order.order.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>duoduo_order.order.user_id</code>.
     */
    public void setUserId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>duoduo_order.order.user_id</code>.
     */
    public String getUserId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>duoduo_order.order.user_type</code>.
     */
    public void setUserType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>duoduo_order.order.user_type</code>.
     */
    public String getUserType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>duoduo_order.order.user_name</code>.
     */
    public void setUserName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>duoduo_order.order.user_name</code>.
     */
    public String getUserName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>duoduo_order.order.spec_desc</code>.
     */
    public void setSpecDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>duoduo_order.order.spec_desc</code>.
     */
    public String getSpecDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>duoduo_order.order.product_id</code>.
     */
    public void setProductId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>duoduo_order.order.product_id</code>.
     */
    public String getProductId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>duoduo_order.order.combo_id</code>.
     */
    public void setComboId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>duoduo_order.order.combo_id</code>.
     */
    public String getComboId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>duoduo_order.order.shop_id</code>.
     */
    public void setShopId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>duoduo_order.order.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>duoduo_order.order.shop_name</code>.
     */
    public void setShopName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>duoduo_order.order.shop_name</code>.
     */
    public String getShopName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>duoduo_order.order.pay_type</code>.
     */
    public void setPayType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>duoduo_order.order.pay_type</code>.
     */
    public String getPayType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>duoduo_order.order.combo_amount</code>.
     */
    public void setComboAmount(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>duoduo_order.order.combo_amount</code>.
     */
    public String getComboAmount() {
        return (String) get(14);
    }

    /**
     * Setter for <code>duoduo_order.order.combo_num</code>.
     */
    public void setComboNum(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>duoduo_order.order.combo_num</code>.
     */
    public String getComboNum() {
        return (String) get(15);
    }

    /**
     * Setter for <code>duoduo_order.order.post_amount</code>.
     */
    public void setPostAmount(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>duoduo_order.order.post_amount</code>.
     */
    public String getPostAmount() {
        return (String) get(16);
    }

    /**
     * Setter for <code>duoduo_order.order.total_amount</code>.
     */
    public void setTotalAmount(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>duoduo_order.order.total_amount</code>.
     */
    public String getTotalAmount() {
        return (String) get(17);
    }

    /**
     * Setter for <code>duoduo_order.order.post_addr</code>.
     */
    public void setPostAddr(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>duoduo_order.order.post_addr</code>.
     */
    public String getPostAddr() {
        return (String) get(18);
    }

    /**
     * Setter for <code>duoduo_order.order.post_code</code>.
     */
    public void setPostCode(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>duoduo_order.order.post_code</code>.
     */
    public String getPostCode() {
        return (String) get(19);
    }

    /**
     * Setter for <code>duoduo_order.order.post_receiver</code>.
     */
    public void setPostReceiver(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>duoduo_order.order.post_receiver</code>.
     */
    public String getPostReceiver() {
        return (String) get(20);
    }

    /**
     * Setter for <code>duoduo_order.order.post_tel</code>.
     */
    public void setPostTel(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>duoduo_order.order.post_tel</code>.
     */
    public String getPostTel() {
        return (String) get(21);
    }

    /**
     * Setter for <code>duoduo_order.order.logistics_id</code>.
     */
    public void setLogisticsId(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>duoduo_order.order.logistics_id</code>.
     */
    public String getLogisticsId() {
        return (String) get(22);
    }

    /**
     * Setter for <code>duoduo_order.order.logistics_code</code>.
     */
    public void setLogisticsCode(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>duoduo_order.order.logistics_code</code>.
     */
    public String getLogisticsCode() {
        return (String) get(23);
    }

    /**
     * Setter for <code>duoduo_order.order.logistics_time</code>.
     */
    public void setLogisticsTime(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>duoduo_order.order.logistics_time</code>.
     */
    public String getLogisticsTime() {
        return (String) get(24);
    }

    /**
     * Setter for <code>duoduo_order.order.receipt_time</code>.
     */
    public void setReceiptTime(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>duoduo_order.order.receipt_time</code>.
     */
    public String getReceiptTime() {
        return (String) get(25);
    }

    /**
     * Setter for <code>duoduo_order.order.buyer_words</code>.
     */
    public void setBuyerWords(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>duoduo_order.order.buyer_words</code>.
     */
    public String getBuyerWords() {
        return (String) get(26);
    }

    /**
     * Setter for <code>duoduo_order.order.cancel_reson</code>.
     */
    public void setCancelReson(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>duoduo_order.order.cancel_reson</code>.
     */
    public String getCancelReson() {
        return (String) get(27);
    }

    /**
     * Setter for <code>duoduo_order.order.remark</code>.
     */
    public void setRemark(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>duoduo_order.order.remark</code>.
     */
    public String getRemark() {
        return (String) get(28);
    }

    /**
     * Setter for <code>duoduo_order.order.order_status</code>.
     */
    public void setOrderStatus(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>duoduo_order.order.order_status</code>.
     */
    public String getOrderStatus() {
        return (String) get(29);
    }

    /**
     * Setter for <code>duoduo_order.order.status</code>.
     */
    public void setStatus(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>duoduo_order.order.status</code>.
     */
    public String getStatus() {
        return (String) get(30);
    }

    /**
     * Setter for <code>duoduo_order.order.create_time</code>.
     */
    public void setCreateTime(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>duoduo_order.order.create_time</code>.
     */
    public String getCreateTime() {
        return (String) get(31);
    }

    /**
     * Setter for <code>duoduo_order.order.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>duoduo_order.order.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(32);
    }

    /**
     * Setter for <code>duoduo_order.order.final_status</code>.
     */
    public void setFinalStatus(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>duoduo_order.order.final_status</code>.
     */
    public String getFinalStatus() {
        return (String) get(33);
    }

    /**
     * Setter for <code>duoduo_order.order.source_id</code>.
     */
    public void setSourceId(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>duoduo_order.order.source_id</code>.
     */
    public String getSourceId() {
        return (String) get(34);
    }

    /**
     * Setter for <code>duoduo_order.order.source_type</code>.
     */
    public void setSourceType(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>duoduo_order.order.source_type</code>.
     */
    public String getSourceType() {
        return (String) get(35);
    }

    /**
     * Setter for <code>duoduo_order.order.seller_words</code>.
     */
    public void setSellerWords(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>duoduo_order.order.seller_words</code>.
     */
    public String getSellerWords() {
        return (String) get(36);
    }

    /**
     * Setter for <code>duoduo_order.order.service</code>.
     */
    public void setService(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>duoduo_order.order.service</code>.
     */
    public String getService() {
        return (String) get(37);
    }

    /**
     * Setter for <code>duoduo_order.order.op_id</code>.
     */
    public void setOpId(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>duoduo_order.order.op_id</code>.
     */
    public String getOpId() {
        return (String) get(38);
    }

    /**
     * Setter for <code>duoduo_order.order.op_time</code>.
     */
    public void setOpTime(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>duoduo_order.order.op_time</code>.
     */
    public String getOpTime() {
        return (String) get(39);
    }

    /**
     * Setter for <code>duoduo_order.order.cancel_remark</code>.
     */
    public void setCancelRemark(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>duoduo_order.order.cancel_remark</code>.
     */
    public String getCancelRemark() {
        return (String) get(40);
    }

    /**
     * Setter for <code>duoduo_order.order.product_name</code>.
     */
    public void setProductName(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>duoduo_order.order.product_name</code>.
     */
    public String getProductName() {
        return (String) get(41);
    }

    /**
     * Setter for <code>duoduo_order.order.repeat</code>.
     */
    public void setRepeat(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>duoduo_order.order.repeat</code>.
     */
    public String getRepeat() {
        return (String) get(42);
    }

    /**
     * Setter for <code>duoduo_order.order.logistics_detail</code>.
     */
    public void setLogisticsDetail(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>duoduo_order.order.logistics_detail</code>.
     */
    public String getLogisticsDetail() {
        return (String) get(43);
    }

    /**
     * Setter for <code>duoduo_order.order.attention</code>.
     */
    public void setAttention(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>duoduo_order.order.attention</code>.
     */
    public String getAttention() {
        return (String) get(44);
    }

    /**
     * Setter for <code>duoduo_order.order.tel_area</code>.
     */
    public void setTelArea(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>duoduo_order.order.tel_area</code>.
     */
    public String getTelArea() {
        return (String) get(45);
    }

    /**
     * Setter for <code>duoduo_order.order.combo_name</code>.
     */
    public void setComboName(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>duoduo_order.order.combo_name</code>.
     */
    public String getComboName() {
        return (String) get(46);
    }

    /**
     * Setter for <code>duoduo_order.order.is_follow_arbitration</code>.
     */
    public void setIsFollowArbitration(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>duoduo_order.order.is_follow_arbitration</code>.
     */
    public String getIsFollowArbitration() {
        return (String) get(47);
    }

    /**
     * Setter for <code>duoduo_order.order.aftersale</code>.
     */
    public void setAftersale(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>duoduo_order.order.aftersale</code>.
     */
    public String getAftersale() {
        return (String) get(48);
    }

    /**
     * Setter for <code>duoduo_order.order.product</code>.
     */
    public void setProduct(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>duoduo_order.order.product</code>.
     */
    public String getProduct() {
        return (String) get(49);
    }

    /**
     * Setter for <code>duoduo_order.order.third_id</code>.
     */
    public void setThirdId(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>duoduo_order.order.third_id</code>.
     */
    public String getThirdId() {
        return (String) get(50);
    }

    /**
     * Setter for <code>duoduo_order.order.urge_cnt</code>.
     */
    public void setUrgeCnt(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>duoduo_order.order.urge_cnt</code>.
     */
    public String getUrgeCnt() {
        return (String) get(51);
    }

    /**
     * Setter for <code>duoduo_order.order.order_json_data</code>.
     */
    public void setOrderJsonData(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>duoduo_order.order.order_json_data</code>.
     */
    public String getOrderJsonData() {
        return (String) get(52);
    }

    /**
     * Setter for <code>duoduo_order.order.account</code>.
     */
    public void setAccount(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>duoduo_order.order.account</code>.
     */
    public String getAccount() {
        return (String) get(53);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Long id, Byte innerStatus, Timestamp innerCreateTime, Timestamp innerUpdateTime, String orderId, String userId, String userType, String userName, String specDesc, String productId, String comboId, String shopId, String shopName, String payType, String comboAmount, String comboNum, String postAmount, String totalAmount, String postAddr, String postCode, String postReceiver, String postTel, String logisticsId, String logisticsCode, String logisticsTime, String receiptTime, String buyerWords, String cancelReson, String remark, String orderStatus, String status, String createTime, String updateTime, String finalStatus, String sourceId, String sourceType, String sellerWords, String service, String opId, String opTime, String cancelRemark, String productName, String repeat, String logisticsDetail, String attention, String telArea, String comboName, String isFollowArbitration, String aftersale, String product, String thirdId, String urgeCnt, String orderJsonData, String account) {
        super(Order.ORDER);

        set(0, id);
        set(1, innerStatus);
        set(2, innerCreateTime);
        set(3, innerUpdateTime);
        set(4, orderId);
        set(5, userId);
        set(6, userType);
        set(7, userName);
        set(8, specDesc);
        set(9, productId);
        set(10, comboId);
        set(11, shopId);
        set(12, shopName);
        set(13, payType);
        set(14, comboAmount);
        set(15, comboNum);
        set(16, postAmount);
        set(17, totalAmount);
        set(18, postAddr);
        set(19, postCode);
        set(20, postReceiver);
        set(21, postTel);
        set(22, logisticsId);
        set(23, logisticsCode);
        set(24, logisticsTime);
        set(25, receiptTime);
        set(26, buyerWords);
        set(27, cancelReson);
        set(28, remark);
        set(29, orderStatus);
        set(30, status);
        set(31, createTime);
        set(32, updateTime);
        set(33, finalStatus);
        set(34, sourceId);
        set(35, sourceType);
        set(36, sellerWords);
        set(37, service);
        set(38, opId);
        set(39, opTime);
        set(40, cancelRemark);
        set(41, productName);
        set(42, repeat);
        set(43, logisticsDetail);
        set(44, attention);
        set(45, telArea);
        set(46, comboName);
        set(47, isFollowArbitration);
        set(48, aftersale);
        set(49, product);
        set(50, thirdId);
        set(51, urgeCnt);
        set(52, orderJsonData);
        set(53, account);
    }
}
